version: '3'
services:
  app:
    build: /docks/.
    ports:
     - "8000:80"
  memcache:
    image: memcached
    ports: 
     - 11211:11211
  elasticseach:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    ports:
     - 9200:9200