version: '2'
services:
  app:
    build: .
    ports:
      - "8000:80"
    links:
      - memcache
      - elasticseach
      - db:mysql
  memcache:
    image: memcached
    expose: 
      - "11211"
    ports: 
      - 7000:11211
  elasticseach:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticseach
    expose:
      - "9200"
    ports:
      - 9000:9200
      - 9100:9300
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports: 
      - "4000:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: hulkshare
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: unitest
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db:mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: unitest
